#pragma once

#include <filesystem>

namespace hotas::launcher {

// A deliberately small native reporter. It is independent of the mapper's
// Qt/QML process and accepts only a local report directory generated by it.
// This non-UI contract is shared with deterministic tests so a missing or
// malformed report never reaches the presentation path as a valid failure.
bool canOpenCrashReport(const std::filesystem::path &reportDirectory);
int runCrashReporter(const std::filesystem::path &reportDirectory);

} // namespace hotas::launcher
