[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$productCatalogPath = Join-Path $root 'docs\catalog\product.json'
$featuresCatalogPath = Join-Path $root 'docs\catalog\features.json'
$versionsCatalogPath = Join-Path $root 'docs\catalog\versions.json'
$versionPath = Join-Path $root 'HOTAS_VERSION'

foreach ($catalogFile in @($productCatalogPath, $featuresCatalogPath, $versionsCatalogPath)) {
    if (-not (Test-Path -LiteralPath $catalogFile -PathType Leaf)) {
        throw "Documentation catalog file is missing: $catalogFile"
    }
}
if (-not (Test-Path -LiteralPath $versionPath -PathType Leaf)) {
    throw "HOTAS_VERSION is missing: $versionPath"
}

$catalog = [pscustomobject]@{
    product = (Get-Content -LiteralPath $productCatalogPath -Raw | ConvertFrom-Json -Depth 100)
    features = (Get-Content -LiteralPath $featuresCatalogPath -Raw | ConvertFrom-Json -Depth 100)
    versions = (Get-Content -LiteralPath $versionsCatalogPath -Raw | ConvertFrom-Json -Depth 100)
}
$version = (Get-Content -LiteralPath $versionPath -Raw).Trim()

if ($version -notmatch '^\d+\.\d+\.\d+$') {
    throw "HOTAS_VERSION must be major.minor.patch; found '$version'."
}
if ($catalog.versions.Count -lt 1) {
    throw 'Documentation catalog must contain at least one version entry.'
}

$latestCatalogVersion = [string]$catalog.versions[$catalog.versions.Count - 1].version
if ($latestCatalogVersion -ne $version) {
    throw "Newest documentation-catalog version '$latestCatalogVersion' does not match HOTAS_VERSION '$version'."
}

function Add-Line {
    param(
        $Lines,
        [string]$Text = ''
    )
    [void]$Lines.Add($Text)
}

function Finish-Document {
    param($Lines)
    return (($Lines -join "`n").TrimEnd("`r", "`n") + "`n")
}

function Build-Readme {
    param($Catalog, [string]$Version)

    $p = $Catalog.product
    $lines = [System.Collections.Generic.List[string]]::new()

    Add-Line $lines '<!-- GENERATED by scripts/sync-documentation.ps1 from docs/catalog/*.json and HOTAS_VERSION. Do not edit this file directly. -->'
    Add-Line $lines
    Add-Line $lines ("# {0}" -f $p.name)
    Add-Line $lines
    Add-Line $lines ("**Current release: v{0}**" -f $Version)
    Add-Line $lines '[Version Overview](docs/Version_Overview.md) · [Complete Features](docs/Features.md)'
    Add-Line $lines
    Add-Line $lines ([string]$p.tagline)
    Add-Line $lines
    Add-Line $lines ([string]$p.summary)
    Add-Line $lines
    if ($null -ne $p.gallery) {
        Add-Line $lines '## Product gallery'
        Add-Line $lines
        Add-Line $lines ("**{0}.** {1}" -f [string]$p.gallery.status, [string]$p.gallery.note)
        Add-Line $lines
        Add-Line $lines ("Capture follow-up: {0}" -f [string]$p.gallery.followUp)
        Add-Line $lines
    }
    Add-Line $lines '## What it is'
    Add-Line $lines
    Add-Line $lines ([string]$p.purpose)
    Add-Line $lines
    Add-Line $lines 'The application sits between a physical DirectInput controller and a vJoy virtual device:'
    Add-Line $lines

    $stepNumber = 1
    foreach ($step in $p.signalPath) {
        Add-Line $lines ("{0}. {1}" -f $stepNumber, $step)
        $stepNumber++
    }

    Add-Line $lines
    Add-Line $lines 'The QML interface observes snapshots and edits configuration; it does not schedule controller output. The mapping worker remains the authority for real-time input processing.'
    Add-Line $lines
    Add-Line $lines '## Design principles'
    Add-Line $lines

    foreach ($principle in $p.principles) {
        Add-Line $lines ("### {0}" -f $principle.name)
        Add-Line $lines
        Add-Line $lines ([string]$principle.description)
        Add-Line $lines
    }

    Add-Line $lines '## Main capabilities'
    Add-Line $lines
    foreach ($feature in $Catalog.features) {
        Add-Line $lines ("- **{0}** — {1}" -f $feature.name, $feature.description)
    }

    Add-Line $lines
    Add-Line $lines 'For the full sectioned feature catalog, see [docs/Features.md](docs/Features.md).'
    Add-Line $lines
    Add-Line $lines '## Installation and first use'
    Add-Line $lines

    $usageNumber = 1
    foreach ($step in $p.usage) {
        Add-Line $lines ("{0}. {1}" -f $usageNumber, $step)
        $usageNumber++
    }

    Add-Line $lines
    Add-Line $lines 'The launcher performs stable-release update checks with short timeouts. Update failures fall back to the installed application, and no updater remains active while mapping.'
    Add-Line $lines
    Add-Line $lines '## Troubleshooting'
    Add-Line $lines
    foreach ($item in $p.troubleshooting) {
        Add-Line $lines ("### {0}" -f $item.symptom)
        Add-Line $lines
        Add-Line $lines ([string]$item.guidance)
        Add-Line $lines
    }
    Add-Line $lines '## Validated and targeted stack'
    Add-Line $lines
    Add-Line $lines '| Category | Hardware / software | Status | Notes |'
    Add-Line $lines '| --- | --- | --- | --- |'
    foreach ($item in $p.testedStack) {
        Add-Line $lines ("| {0} | {1} | {2} | {3} |" -f $item.category, $item.item, $item.status, $item.notes)
    }

    Add-Line $lines
    Add-Line $lines '## Hardware support'
    Add-Line $lines
    Add-Line $lines 'The structured support matrix distinguishes validated hardware from expected-but-unverified devices and lists the exact reporting boundary: [Hardware Compatibility](docs/Hardware_Compatibility.md).'

    Add-Line $lines
    Add-Line $lines '## Runtime safety'
    Add-Line $lines
    Add-Line $lines '- **Mapping Off** deliberately centers available virtual axes, releases virtual buttons, and centers POVs.'
    Add-Line $lines '- Controller disconnect suspends mapping and clears unsafe transient state.'
    Add-Line $lines '- Unsupported or disabled virtual targets are parked rather than left with stale output.'
    Add-Line $lines '- Mapping-control buttons are edge-triggered so a held button cannot repeatedly toggle the mapper.'
    Add-Line $lines '- Automation drafts remain disabled until complete, valid, saved, and compiled.'
    Add-Line $lines
    Add-Line $lines '## Configuration model'
    Add-Line $lines
    Add-Line $lines 'Profiles own the gameplay mapping configuration: routes, axis domains, deadzones, hysteresis, inversion, output limits, curves, button routes, and custom names. Physical calibration, device preferences, dependency state, and Disabled Axis Value are global. Runtime-only Hold/Toggle overrides, Automation latches, and timers are never saved.'
    Add-Line $lines
    Add-Line $lines '## Build and development'
    Add-Line $lines
    Add-Line $lines 'Requirements:'
    Add-Line $lines
    Add-Line $lines '- Windows 10 or 11'
    Add-Line $lines '- CMake 3.21+'
    Add-Line $lines '- C++20-capable Visual Studio/MSVC environment'
    Add-Line $lines '- Qt 6.5+ with Core, Gui, Network, Qml, Quick, QuickControls2, and Test'
    Add-Line $lines '- vJoy for virtual output'
    Add-Line $lines
    Add-Line $lines 'Typical local build:'
    Add-Line $lines
    Add-Line $lines '```powershell'
    Add-Line $lines 'cmake -S . -B build-release -DCMAKE_PREFIX_PATH=C:\Qt\6.5.3\msvc2019_64'
    Add-Line $lines 'cmake --build build-release --config Release'
    Add-Line $lines 'ctest --test-dir build-release --output-on-failure -C Release'
    Add-Line $lines '.\build-release\HOTAS BF6.exe'
    Add-Line $lines '```'
    Add-Line $lines
    Add-Line $lines 'The release workflow additionally performs QML validation, headless tests, a synthetic mapping benchmark, dependency/resource checks, Qt deployment, installer build, install/uninstall smoke testing, final installer verification when trusted signing is enabled, checksums, update-manifest generation, and GitHub Release publication.'
    Add-Line $lines
    Add-Line $lines '## Documentation'
    Add-Line $lines

    foreach ($document in $p.documentation) {
        Add-Line $lines ("- **[{0}]({1})** — {2}" -f $document.name, $document.path, $document.description)
    }

    Add-Line $lines
    Add-Line $lines '## License'
    Add-Line $lines
    Add-Line $lines ("HOTAS BF6 Simple source is available under the [{0}]({1}). Dependency and trademark boundaries are documented in [{2}]({3})." -f $p.license.name, $p.license.path, 'Third-Party Notices', $p.license.noticesPath)

    Add-Line $lines
    Add-Line $lines '## Documentation maintenance'
    Add-Line $lines
    Add-Line $lines 'README.md, docs/Features.md, and docs/Version_Overview.md are generated from the structured files in `docs/catalog/` plus `HOTAS_VERSION`.'
    Add-Line $lines
    Add-Line $lines 'Run `.\scripts\sync-documentation.ps1` after changing product, feature, or version catalog data. The Documentation Check workflow runs on pull requests, pushes to `main`, tags, and manual dispatch and fails if any generated document is stale.'
    Add-Line $lines
    Add-Line $lines 'The generator also requires the newest `docs/catalog/versions.json` entry to match `HOTAS_VERSION`, so a version bump cannot pass documentation validation without a corresponding Version Overview entry.'
    Add-Line $lines
    Add-Line $lines 'When adding or changing a user-visible capability or release, update the appropriate file in `docs/catalog/`; do not hand-edit the generated documents.'
    Add-Line $lines

    return (Finish-Document $lines)
}

function Build-Features {
    param($Catalog, [string]$Version)

    $lines = [System.Collections.Generic.List[string]]::new()

    Add-Line $lines '<!-- GENERATED by scripts/sync-documentation.ps1 from docs/catalog/*.json and HOTAS_VERSION. Do not edit this file directly. -->'
    Add-Line $lines
    Add-Line $lines '# HOTAS BF6 Simple — Features'
    Add-Line $lines
    Add-Line $lines ("**Current release: v{0}**" -f $Version)
    Add-Line $lines
    Add-Line $lines 'This document is the authoritative sectioned catalog of user-visible and engineering features in the current application. Historical changes belong in [Version_Overview.md](Version_Overview.md).'
    Add-Line $lines
    Add-Line $lines '## Feature index'
    Add-Line $lines

    $featureNumber = 1
    foreach ($feature in $Catalog.features) {
        Add-Line $lines ("{0}. {1}" -f $featureNumber, $feature.name)
        $featureNumber++
    }

    Add-Line $lines
    foreach ($feature in $Catalog.features) {
        Add-Line $lines ("## {0}" -f $feature.name)
        Add-Line $lines
        Add-Line $lines ([string]$feature.description)
        Add-Line $lines
        foreach ($subfeature in $feature.subfeatures) {
            Add-Line $lines ("- {0}" -f $subfeature)
        }
        Add-Line $lines
    }

    Add-Line $lines '## Maintenance'
    Add-Line $lines
    Add-Line $lines 'This file is generated from `docs/catalog/features.json`. Update that catalog when a feature is added, removed, renamed, or materially changed; the documentation workflow regenerates this file automatically.'
    Add-Line $lines

    return (Finish-Document $lines)
}

function Build-VersionOverview {
    param($Catalog, [string]$Version)

    $lines = [System.Collections.Generic.List[string]]::new()

    Add-Line $lines '<!-- GENERATED by scripts/sync-documentation.ps1 from docs/catalog/*.json and HOTAS_VERSION. Do not edit this file directly. -->'
    Add-Line $lines
    Add-Line $lines '# HOTAS BF6 Simple — Version Overview'
    Add-Line $lines
    Add-Line $lines ("**Current release: v{0}**" -f $Version)
    Add-Line $lines
    Add-Line $lines 'This document summarizes what each published project version added. It is intentionally separated from the README so the README can describe the current product instead of becoming a geological core sample of old release notes.'
    Add-Line $lines
    Add-Line $lines 'Versions are shown newest first.'
    Add-Line $lines

    for ($index = $Catalog.versions.Count - 1; $index -ge 0; $index--) {
        $release = $Catalog.versions[$index]
        Add-Line $lines ("## v{0} — {1}" -f $release.version, $release.title)
        Add-Line $lines
        Add-Line $lines ([string]$release.summary)
        Add-Line $lines
        foreach ($highlight in $release.highlights) {
            Add-Line $lines ("- {0}" -f $highlight)
        }
        Add-Line $lines
    }

    Add-Line $lines '## Maintenance'
    Add-Line $lines
    Add-Line $lines 'This file is generated from `docs/catalog/versions.json`. Add each new published version there and update `HOTAS_VERSION`; the documentation workflow regenerates this overview and verifies that the newest catalog entry matches the current version.'
    Add-Line $lines

    return (Finish-Document $lines)
}

function Build-HardwareCompatibility {
    param($Catalog, [string]$Version)

    $p = $Catalog.product
    $lines = [System.Collections.Generic.List[string]]::new()
    Add-Line $lines '<!-- GENERATED by scripts/sync-documentation.ps1 from docs/catalog/product.json and HOTAS_VERSION. Do not edit this file directly. -->'
    Add-Line $lines
    Add-Line $lines '# HOTAS BF6 Simple — Hardware Compatibility'
    Add-Line $lines
    Add-Line $lines ("**Current release: v{0}**" -f $Version)
    Add-Line $lines
    Add-Line $lines 'This matrix records only supported states and evidence boundaries. “Expected / Unverified” is not a tested or endorsed claim.'
    Add-Line $lines
    Add-Line $lines '## Status definitions'
    Add-Line $lines
    Add-Line $lines '| Status | Meaning |'
    Add-Line $lines '| --- | --- |'
    foreach ($status in $p.hardwareStatusDefinitions) {
        Add-Line $lines ("| {0} | {1} |" -f $status.status, $status.meaning)
    }
    Add-Line $lines
    Add-Line $lines '## Matrix'
    Add-Line $lines
    Add-Line $lines '| Manufacturer | Device / model | Connection architecture | Axes | Buttons | POVs | Status | Windows | HOTAS BF6 | Notes |'
    Add-Line $lines '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |'
    foreach ($item in $p.hardwareMatrix) {
        Add-Line $lines ("| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} | {9} |" -f $item.manufacturer, $item.model, $item.architecture, $item.axes, $item.buttons, $item.povs, $item.status, $item.windows, $item.hotasVersion, $item.notes)
    }
    Add-Line $lines
    Add-Line $lines '## Adding evidence'
    Add-Line $lines
    Add-Line $lines 'Use Controller Setup to capture the selected controller''s capability summary. A hardware status may move to Validated only with a recorded Windows version, HOTAS BF6 version, controller identity, and a real controller-to-vJoy acceptance result. CI and synthetic tests do not establish that result.'
    Add-Line $lines
    Add-Line $lines '## Maintenance'
    Add-Line $lines
    Add-Line $lines 'This file is generated from `docs/catalog/product.json`. Update that structured matrix and run `..\scripts\sync-documentation.ps1`; do not hand-edit this document.'
    Add-Line $lines
    return (Finish-Document $lines)
}

function Build-Bf6Compatibility {
    param($Catalog, [string]$Version)

    $p = $Catalog.product
    $c = $p.compatibility
    $lines = [System.Collections.Generic.List[string]]::new()
    Add-Line $lines '<!-- GENERATED by scripts/sync-documentation.ps1 from docs/catalog/product.json and HOTAS_VERSION. Do not edit this file directly. -->'
    Add-Line $lines
    Add-Line $lines '# HOTAS BF6 Simple — Battlefield 6 Compatibility'
    Add-Line $lines
    Add-Line $lines ("**Current release: v{0}**" -f $Version)
    Add-Line $lines
    Add-Line $lines '## Official / anticheat boundary'
    Add-Line $lines
    Add-Line $lines ([string]$c.official)
    Add-Line $lines
    Add-Line $lines '## What this utility does'
    Add-Line $lines
    Add-Line $lines ([string]$c.utility)
    Add-Line $lines
    Add-Line $lines '## Verified versus unverified'
    Add-Line $lines
    Add-Line $lines ([string]$c.verified)
    Add-Line $lines
    Add-Line $lines '## Windows and signing'
    Add-Line $lines
    Add-Line $lines ([string]$c.windows)
    Add-Line $lines
    Add-Line $lines '## Reporting a compatibility regression'
    Add-Line $lines
    Add-Line $lines ([string]$c.reporting)
    Add-Line $lines
    Add-Line $lines '## Maintenance'
    Add-Line $lines
    Add-Line $lines 'This document is generated from `docs/catalog/product.json`. Keep official claims, internal tests, and community reports separated when updating it.'
    Add-Line $lines
    return (Finish-Document $lines)
}

$targets = [ordered]@{}
$targets[(Join-Path $root 'README.md')] = (Build-Readme $catalog $version)
$targets[(Join-Path $root 'docs\Features.md')] = (Build-Features $catalog $version)
$targets[(Join-Path $root 'docs\Version_Overview.md')] = (Build-VersionOverview $catalog $version)
$targets[(Join-Path $root 'docs\Hardware_Compatibility.md')] = (Build-HardwareCompatibility $catalog $version)
$targets[(Join-Path $root 'docs\BF6_Compatibility.md')] = (Build-Bf6Compatibility $catalog $version)

if ($Check) {
    $drift = [System.Collections.Generic.List[string]]::new()
    foreach ($entry in $targets.GetEnumerator()) {
        if (-not (Test-Path -LiteralPath $entry.Key -PathType Leaf)) {
            [void]$drift.Add($entry.Key)
            continue
        }
        $actual = (Get-Content -LiteralPath $entry.Key -Raw) -replace "`r`n", "`n"
        $expected = ([string]$entry.Value) -replace "`r`n", "`n"
        if ($actual -ne $expected) {
            [void]$drift.Add($entry.Key)
        }
    }

    if ($drift.Count -gt 0) {
        throw ("Generated documentation is stale: " + ($drift -join ', ') + ". Run .\scripts\sync-documentation.ps1 and commit the generated files.")
    }

    Write-Host "Generated documentation is synchronized for v$version."
    exit 0
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
foreach ($entry in $targets.GetEnumerator()) {
    [System.IO.File]::WriteAllText($entry.Key, $entry.Value, $utf8NoBom)
    Write-Host ("Updated {0}" -f (Resolve-Path -LiteralPath $entry.Key).Path)
}
